version: '3.7'
volumes:
  pg_project:

services:
  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=2812tyHx_8
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pg_project:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin4_container3
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: bebeshkomail@mail.ru
      PGADMIN_DEFAULT_PASSWORD: 2812tyHx_8
    ports:
      - "5050:80"
#  my-springboot-container:
#    image: proj-docker-compose:1
#    build:
#      context: ./
#      dockerfile: Dockerfile
#    volumes:
#      - /data/my-springboot-container
#    ports:
#      - "8080:8080"